/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.laramara.repositorio;

import br.gov.laramara.dto.Colaborador;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author laramara
 */
public class RepositorioBase {

    public List<Colaborador> obterTodos() {

        return Arrays.asList(
                new Colaborador("AC Barqueiro", "6405", "REL.INSTITUCIONAIS","LARAMARA"),
                new Colaborador("Adelson Braga", "6495", "EVENTOS","LARAMARA"),
                new Colaborador("Adilson Guimaraes", "6710", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Adriana Araujo", "6445", "RECEPCAO CTO","LARAMARA"),
                new Colaborador("Adriana Barsot", "6472", "CTO","LARAMARA"),
                new Colaborador("Adriana Contabilidade", "6780", "MARVIC´S","MARVIC´S"),
                new Colaborador("Alba Regiane de Jesus", "6768", "BRINCANTO","LARAMARA"),
                new Colaborador("Aldenir Souza", "6716", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Alex Costa", "6450", "CPD","LARAMARA"),
                new Colaborador("Alexandro Ribeiro", "6760", "CTO","LARAMARA"),
                new Colaborador("Amanda BulbarelliLourenço", "6477", "CTO","LARAMARA"),
                new Colaborador("Amanda Silva", "6444", "MARVIC´S","MARVIC´S"),
                new Colaborador("Ana Marcia Fernandes", "6473", "CTO","LARAMARA"),
                new Colaborador("Ana Paula Braga", "6766", "CTO","LARAMARA"),
                new Colaborador("Ana Vaz", "6783", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Anderson Batissta", "6457", "CTO","LARAMARA"),
                new Colaborador("Anderson GalvÆo", "6414", "CONTABILIDADE","LARAMARA"),
                new Colaborador("Anderson Silva", "6484", "FINANCEIRO","LARAMARA"),
                new Colaborador("Andrea Oliveira", "6441", "MARVIC´S","MARVIC´S"),
                new Colaborador("Andr‚ Silva", "6762", "FINANCEIRO","LARAMARA"),
                new Colaborador("Angela Paiva", "6496", "CTO","LARAMARA"),
                new Colaborador("Anna Gomes", "6463", "BRINCANTO","LARAMARA"),
                new Colaborador("Avalia‡Æo III", "6451", "CTO","LARAMARA"),
                new Colaborador("Avalia‡Æo III", "6777", "CTO","LARAMARA"),
                new Colaborador("Beto Pereira", "6480", "LARATEC","LARAMARA"),
                new Colaborador("Bia", "6452", "CTO","LARAMARA"),
                new Colaborador("Bianca Peres", "6711", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Briquedoteca", "6468", "CTO","LARAMARA"),
                new Colaborador("Carina Silva", "6726", "MARVIC´S","MARVIC´S"),
                new Colaborador("Carlos Kafka", "6489", "TI LARAMARA","LARAMARA"),
                new Colaborador("Caroline (LojaLARATEC)", "6458", "LARATEC","LARAMARA"),
                new Colaborador("Casinha de AVD", "6494", "CTO","LARAMARA"),
                new Colaborador("Cecilia Oka", "6462", "PROCEJA","LARAMARA"),
                new Colaborador("Celia Silva", "6712", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Cida", "6479", "CTO","LARAMARA"),
                new Colaborador("Clara Adamo", "6438", "REFEITORIO","LARAMARA"),
                new Colaborador("Claudia Val", "6615", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Cleyton Jesus", "6419", "TRIBUTARIO","LARAMARA"),
                new Colaborador("Cristina Takahashi", "6499", "PROCEJA","LARAMARA"),
                new Colaborador("Daniela Danielenco", "6409", "FINANCEIRO","LARAMARA"),
                new Colaborador("Daniela Rueda", "6612", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Daniela Val", "6767", "CTO","LARAMARA"),
                new Colaborador("Danilo", "6790", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Edineia Santana", "6412", "EVENTOS","LARAMARA"),
                new Colaborador("Ednaldo Silva", "6476", "TI MARVIC´S","MARVIC´S"),
                new Colaborador("Elaine Santos", "6420", "MARVIC´S","MARVIC´S"),
                new Colaborador("Elaine Teixeira", "6455", "RECEPCAO CTO","LARAMARA"),
                new Colaborador("Eliana Ormelezi", "6428", "CTO","LARAMARA"),
                new Colaborador("Eliana Paulino", "6426", "CTO","LARAMARA"),
                new Colaborador("Elizabeth Santos", "6486/6416", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Ellen Mota", "6490", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Erika Machado", "6482", "MARVIC´S","MARVIC´S"),
                new Colaborador("Fabio Brunharo", "6464", "MAQUINA BRAILLE","LARAMARA"),
                new Colaborador("Fabio Santos", "6425", "PROCEJA","LARAMARA"),
                new Colaborador("Farmácia (Drogaria São Paulo)", "4003-3393", "OUTROS","LARAMARA"),
                new Colaborador("Fax (Brincanto)", "3662-1042", "BRINCANTO","LARAMARA"),
                new Colaborador("Fax (Grafica Barra Funda)", "3825-9024", "GRAFICA"," GRAFICA LARAMARA"),
                new Colaborador("Fax (Presidˆncia)", "3824-9108", "PRESIDENCIA","LARAMARA"),
                new Colaborador("Fax (RH MARVIC´S)", "3661-1201", "RH MARVIC´S","MARVIC´S"),
                new Colaborador("Fax ADM", "3662-0551", "TRIBUTARIO","LARAMARA"),
                new Colaborador("Fernanda Jarzinski", "3663-0016", "RECEPCAO GRAFICA","GRAFICA LARAMARA"),
                new Colaborador("Fernando -Washington-Maicon", "6432", "MAQUINA BRAILLE","LARAMARA"),
                new Colaborador("Fernando Lima", "6423", "TRIBUTARIO","LARAMARA"),
                new Colaborador("Ferramentaria-Estoque", "6753/6771", "MAQUINA BRAILLE","LARAMARA"),
                new Colaborador("Gerusa Silva", "6447", "FINANCEIRO","LARAMARA"),
                new Colaborador("Gisele Siqueira", "6763", "RH","LARAMARA"),
                new Colaborador("Glaucia Munhoz", "6486/6416", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Gra‡a", "6472", "CTO","LARAMARA"),
                new Colaborador("Hotel Unique", "3055-4700", "UNIQUE SÃO PAULO","UNIQUE"),
                new Colaborador("H‚bio Nascimento", "6784", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Isabel Souza", "6475", "CTO","LARAMARA"),
                new Colaborador("Janice Punko", "6728", "CONTABILIDADE","LARAMARA"),
                new Colaborador("Jefferson Pena", "6431", "RH","LARAMARA"),
                new Colaborador("Joel (Estacionamento)", "6781", "OUTROS","LARAMARA"),
                new Colaborador("Jorge Santos", "6413", "CONTABILIDADE","LARAMARA"),
                new Colaborador("Josu‚ Cust¢dio", "6448", "TRIBUTARIO","LARAMARA"),
                new Colaborador("JoÆo Felippe", "6474", "CTO","LARAMARA"),
                new Colaborador("JoÆo Tavares", "6440", "MARVIC´S","MARVIC´S"),
                new Colaborador("Juliana Carvalho", "6613/6614", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Juliana Silva", "6465", "RECEPCAO CTO","LARAMARA"),
                new Colaborador("Juliane trindade", "6470", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Junia Gomes", "6479", "CTO","LARAMARA"),
                new Colaborador("Keli Matheus", "6454", "CTO","LARAMARA"),
                new Colaborador("Kelly", "6418", "MAQUINA BRAILLE","LARAMARA"),
                new Colaborador("Kelly Assump‡Æo", "6418", "MAQUINA BRAILLE","LARAMARA"),
                new Colaborador("Laramara Assoc. Bras.", "3660-6400", "TI LARAMARA","LARAMARA"),
                new Colaborador("Leonardo Ferreira", "6435", "LARATEC","LARAMARA"),
                new Colaborador("LeTIcia Galindo", "6775", "MARVIC´S","MARVIC´S"),
                new Colaborador("Lilia Giacomini", "6754", "PROCEJA","LARAMARA"),
                new Colaborador("Lisley Mazo", "6430/9", "RECEPCAO ADM","LARAMARA"),
                new Colaborador("Lucas Benedito (Boy)", "6415", "SERVIÇOS","LARAMARA"),
                new Colaborador("Lucas Castro", "6785", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Luis Rotatori", "6429", "SEGURANÇA TRABALHO","LARAMARA"),
                new Colaborador("Luis Sposito", "6449", "SERVIÇOS","LARAMARA"),
                new Colaborador("Luis Sposito (Nextel)", "7723-5464", "SERVIÇOS","LARAMARA"),
                new Colaborador("Luiz Souza", "6401", "MARVIC´S","MARVIC´S"),
                new Colaborador("Luiz Xavier", "6491", "ASSISTENCIA TECNICA","LARAMARA"),
                new Colaborador("Mara Melo", "6427", "PROCEJA","LARAMARA"),
                new Colaborador("Mara Siaulys", "6460", "PRESIDENCIA","LARAMARA"),
                new Colaborador("Marcela Silva", "6408", "DESENVOLVIMENTO INSTITUCIONAL","LARAMARA"),
                new Colaborador("Marcos Monteiro", "6751", "SERVIÇOS","LARAMARA"),
                new Colaborador("Maria Elisa", "6774", "BAZAR","LARAMARA"),
                new Colaborador("Marina Alves", "6410", "RH","LARAMARA"),
                new Colaborador("Marta Campos", "6402/6403", "DIRETORIA","LARAMARA"),
                new Colaborador("Mateus / Vitoria", "6424", "TI LARAMARA","LARAMARA"),
                new Colaborador("Mateus Pessoa", "6717", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Mayara Silva", "6483", "MARVIC´S","MARVIC´S"),
                new Colaborador("Mayumi Sei", "6453", "CTO","LARAMARA"),
                new Colaborador("Nelma Meo", "6467", "CTO","LARAMARA"),
                new Colaborador("Paula Reyes Alves", "6727", "MARVIC´S","MARVIC´S"),
                new Colaborador("Paula Silveira", "6782", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Paulo Bandeira", "6489", "TI LARAMARA","LARAMARA"),
                new Colaborador("Leone Pizolli", "6489", "TI LARAMARA","LARAMARA"),
                new Colaborador("Paulo Cunha (Mineiro)", "6478", "SERVIÇOS","LARAMARA"),
                new Colaborador("Paulo Ember", "6772", "RECEBIMENTO EXPEDI€ÇO","LARAMARA"),
                new Colaborador("Rafael Pereira", "6713", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Refeitorio (Compras)", "3667-1778", "REFEITORIO","LARAMARA"),
                new Colaborador("Regiane Anuncio", "6718", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Renato Jos‚", "6779", "IMPRESSÃO BRAILLE","LARAMARA"),
                new Colaborador("Ricardo", "6485", "DESENVOLVIMENTO INSTITUCIONAL","LARAMARA"),
                new Colaborador("Ricardo Araujo", "6422", "TI LARAMARA","LARAMARA"),
                new Colaborador("Robert Mortimer", "6417", "LARATEC","LARAMARA"),
                new Colaborador("Rodrigo Lopes", "6765", "IMPRESSÃO BRAILLE","LARAMARA"),
                new Colaborador("Rosana Furtado", "6459", "CTO","LARAMARA"),
                new Colaborador("Rosangela Mota", "6613/6614", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("Rosangela Valtner", "6407", "FINANCEIRO","LARAMARA"),
                new Colaborador("Rubens Leme", "6493", "TI LARAMARA","LARAMARA"),
                new Colaborador("R“ Barqueiro", "6406", "REL.INSTITUCIONAIS","LARAMARA"),
                new Colaborador("sala 2- terreo", "6442", "ASSISTENCIA TECNICA","LARAMARA"),
                new Colaborador("Sala Reuniao ADM", "6757", "CONTABILIDADE","LARAMARA"),
                new Colaborador("Sandra Regina", "6461", "PRESIDENCIA","LARAMARA"),
                new Colaborador("Sandra Regina (Nextel)", "7858-6904", "PRESIDENCIA","LARAMARA"),
                new Colaborador("Selma Bruschi", "6437", "FINANCEIRO","LARAMARA"),
                new Colaborador("Silverlei Vieira", "6475", "CTO","LARAMARA"),
                new Colaborador("Silvia Andreossi", "6475", "CTO","LARAMARA"),
                new Colaborador("Silvia Gomes", "6443", "MARVIC´S","MARVIC´S"),
                new Colaborador("Sonia Gondo", "6479", "CTO","LARAMARA"),
                new Colaborador("Sr Adelino (Didi)", "6752", "REFEITORIO","LARAMARA"),
                new Colaborador("Sueli", "6770", "GRAFICA ADM","GRAFICA LARAMARA"),
                new Colaborador("Suellen Ribeiro", "6434", "DESENVOLVIMENTO INSTITUCIONAL","LARAMARA"),
                new Colaborador("TaTIana Pereira", "6725", "MARVIC´S","MARVIC´S"),
                new Colaborador("Taxi (Cons. Brotero)", "3667-6486", "OUTROS","LARAMARA"),
                new Colaborador("Telefone Direto(Contribuinte)", "3825-2125", "CENTRAL DE DOAÇÕES","LARAMARA"),
                new Colaborador("TI Suporte", "6424", "TI LARAMARA","LARAMARA"),
                new Colaborador("Tiago Nunes", "6714", "COMPRAS CORPORATIVA","LARAMARA"),
                new Colaborador("Unique Garden", "4486-8700", "UNIQUE GARDEN","UNIQUE"),
                new Colaborador("Unique Garden (Chal‚)", "4486-3372", "UNIQUE GARDEN","UNIQUE"),
                new Colaborador("Vanessa Martins", "6430/9", "RECEPCAO ADM","LARAMARA"),
                new Colaborador("Vera Campos", "6488", "MARVIC´S","MARVIC´S"),
                new Colaborador("Vera Lucia", "6764/6466", "CTO","LARAMARA"),
                new Colaborador("Vera Pereira", "6456", "CTO","LARAMARA"),
                new Colaborador("Ver“nica Mota", "6497", "CTO","LARAMARA"),
                new Colaborador("Volunt rios", "6481", "CTO","LARAMARA"),
                new Colaborador("Wellington", "6446", "RH","LARAMARA"),
                new Colaborador("William Rodrigues", "6425", "PROCEJA","LARAMARA"),
                new Colaborador("Willy Scholz", "6776", "UNIQUE SÃO PAULO","UNIQUE"),
                new Colaborador("Yvens", "6425", "PROCEJA","LARAMARA")
        );

    }
}
